### ISSUE TITLE
How to install and run this project?

### ISSUE THREAD

**Issue by 1553545365** [Laiqingsi/CLOCs_LQS#2]
您好，我目前已经完成了OpenPCDet的运行（在其他文件夹中），从上交云盘中下载了您提供的2D与3D目标检测结果，可是CLOCs工程中没有setup.py，使得它不能被安装并运行，我应该如何处理呢？真心需要您的帮助，可以麻烦添加一下联系方式吗？我的邮箱是1553545365@qq.com

Hello, I have finished running OpenPCDet (in other folders) and downloaded your 2D and 3D target detection results from the Cloud, but there is no setup.py in the CLOCs project, which makes it impossible to install and run. What should I do? I really need your help. My E-mail is 1553545365@qq.com, would you like to add some contact information?

**Comment by Laiqingsi** [comment]
Hi, thank you for your attention. I am sorry that  I did not response you in time. You can add the code path to your ".bashrc" file, so that you can run it properly.

**Comment by 1553545365** [comment]
> 

非常感谢你的回复，您说的方案能不能更具体一点呢？这几个月以来，我尝试过多种手段来运行它，可是都失败了。
Thank you very much for your reply. Can your plan how to run it more specific? Over the past few months, I have tried many ways to run it, but  all failed.

**Comment by Laiqingsi** [comment]
I have updated the readme file, you can check it. If you still have questions, don't hestitate to ask me. Hope this can help you.
