### ISSUE TITLE
 3D detection results

### ISSUE THREAD

**Issue by ShiluYang96** [Laiqingsi/CLOCs_LQS#3]
Hallo Laiqingsi,

Thanks for your great implementation. Could you provide the 3D detection results from SECOND? The link you post in readme is not reachable.

**Comment by Laiqingsi** [comment]
I will upload it to GoogleDrive, but it needs a little time. After I upload it, I will update it in readme. Thank you for your attention.

**Comment by Laiqingsi** [comment]
I have uploaded the data to Googledrive([2d data](https://drive.google.com/file/d/11_OvYFpsK12bn_TRDElbYmnTqmvyfpG-/view) and [3d data](https://drive.google.com/file/d/1tzajKim1Uh65zn4ABVHGC5TceK-IaWg_/view)). Hope this can help you.

**Comment by wangxianggang1997** [comment]
> 我已将数据上传到 Googledrive（[2d 数据](https://drive.google.com/file/d/11_OvYFpsK12bn_TRDElbYmnTqmvyfpG-/view)和[3d 数据](https://drive.google.com/file/d/1tzajKim1Uh65zn4ABVHGC5TceK-IaWg_/view)）。希望这可以帮到你。

The 3D inspection data link has expired. Can you re-upload it?
