### ISSUE TITLE
How to get no NMS results ?

### ISSUE THREAD

**Issue by ChenXuhuaX** [Laiqingsi/CLOCs_LQS#7]
I trained a second_car network , it works well. 
![1650985821(1)](https://user-images.githubusercontent.com/41030991/165332830-73e3a986-eff9-45bc-9432-1f08c0e9824b.png)

when I use the second-predict.yaml to get no NMS resluts, I got the scores like this:
![1650985230(1)](https://user-images.githubusercontent.com/41030991/165331813-b6c3974f-124e-43fa-9f83-f32013a4d17a.png)

So,how to get no NMS results in pcdet? Could you share  the skills ,please?

**Comment by ChenXuhuaX** [comment]
I have solve this problem,Thanks.

**Comment by BingqiShen** [comment]
> 

hi~I have the same question and could you please tell me how to solve it on openPCDet？thanks a lot!!!
